### ISSUE TITLE
error

### ISSUE THREAD

**Issue by DenzelCode** [thebigsmileXD/BossBarAPI#38] opened 2017-09-07 14:51 UTC
[09:51:10] [Server thread/CRITICAL]: TypeError: "Argument 1 passed to pocketmine\utils\BinaryStream::putLFloat() must be of the type float, null given, called in C:\Users\ubbly\Documents\NetBeans\MasterCraft\src\pocketmine\network\mcpe\protocol\DataPacket.php on line 354" (EXCEPTION) in "src/pocketmine/utils/BinaryStream" at line 188

**Comment by thebigsmileXD** [comment] 2017-09-07 16:07
Duplicate of https://github.com/thebigsmileXD/BossBarAPI/issues/37

**Closed** 2017-09-07 16:08 UTC
Labels: duplicate, invalid
